services:
  k9:
    build:
      context: .
      dockerfile: dockerfile/k9.Dockerfile
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
      JVM_ARGS: "${JVM_ARGS}"
    volumes:
      - type: volume
        source: k9-data
        target: /app/data
    networks:
      - default

volumes:
  k9-data:

networks:
  default:
